#!/usr/bin/env python3
"""
R689 -- the release ships ONE core. R442's `published_five` is retracted as a description of CoVal.

CHECK #290 ON R688's NEXT LINE -- TWO DEFECTS, ONE OF THEM ITS PREMISE.
  ① CITATION: it cites "R519's admitted set" for the four arms ③ removes. `R519.admitted` is the
     FIVE. The four are `R404.admitted_2 − R404.admitted_2a`. Fourth citation defect in this arc,
     and the numbers were right each time — it is the pointer that rots.
  ② PREMISE: it proposed reading "CoVal's release manifest". There is none; the release ships DATA,
     documented by `data/DATASET_CARD.md` — which has been on disk throughout, while R688 wrote
     into its impossibility register that settling this "needs the release's own text".
     ⭐ §4's "a wall never checked": a permanent limit that was a query nobody ran.

ESTIMAND        A: of R442's `PUBLISHED_FIVE`, how many appear in the release's own documentation?
                B: does the card state the core's SIZE distribution, and what is the modal size?
IDENTIFICATION  ⚠ "absent from the card" is NOT "not published" — the card documents the DATA and
                enumerates no comparison arms. The load-bearing evidence is the PAIR: absent from the
                card AND generated by our own corebench source.
SCOPE           population : the 5 members of PUBLISHED_FIVE + the 4 arms ③ removes
                instrument : literal search over data/DATASET_CARD.md + provenance grep over
                             corebench/*.py
                             instrument unit = A NAME OCCURRENCE
                             claim unit      = AN ARM THE RELEASE PUBLISHES
                             ⚠ NOT EQUAL — hence the pair requirement above.
                baseline   : R442's hard-coded PUBLISHED_FIVE (run.py:107, no cited source)
                regime     : the home release as shipped in data/
WORLDS          A OUR CONSTRUCTIONS: the card names one core; the rest are ours, so a definition
                  tested against "the published five" was tested against objects we built.
                B GENUINELY PUBLISHED: the card names them, and PUBLISHED_FIVE is defensible.
KILL            the card names >=3 of the five -> world B, no retraction.
POSITIVE CTRL   `rubric` is KNOWN to be in the card; a grep is an instrument and must be shown able
                to return non-zero.
g=0             `topabs_k4` must return 0 against that same instrument.
NEGATIVE CTRL   a nonsense token returns 0.
PLACEBO         run twice identical.
ARTIFACT        results/release_says.json
IMPOSSIBLE      whether CoVal INTENDED any of our arms as a baseline is not in the data; the card
                documents the release, not our comparisons.
"""
from __future__ import annotations
import json, pathlib, re, subprocess, sys

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE
while not (ROOT / "assurance").is_dir() and ROOT != ROOT.parent:
    ROOT = ROOT.parent
ARC = HERE.parent
CARD = ROOT / "data" / "DATASET_CARD.md"
PUBLISHED = ["coval_core", "topabs_k4", "topvar_k4", "topw_k4", "topwvar_k4"]
REMOVES3 = ["greedy_k4_fit1", "indep_k4_fit1", "oracle_k4", "oracle_k4_fit1"]


def occurs(txt, term): return len(re.findall(re.escape(term), txt, re.I))


def main() -> int:
    if not CARD.is_file():
        print("UNRUNNABLE: data/DATASET_CARD.md absent. Exit 2, never 0."); return 2
    txt = CARD.read_text(errors="ignore")

    print("─── CONTROLS (a grep is an instrument) ───")
    pos = occurs(txt, "rubric")
    print(f"  POSITIVE  a term KNOWN to be in the card (`rubric`) -> {pos} hits -> "
          f"{'PASS — the instrument can return non-zero' if pos > 0 else '⛔ FAIL — silence, not measurement'}")
    g0 = occurs(txt, "topabs_k4")
    print(f"  g=0       a term expected ABSENT (`topabs_k4`) -> {g0} -> "
          f"{'PASS' if g0 == 0 else '⛔ FAIL'}")
    neg = occurs(txt, "zzq_no_such_token")
    print(f"  NEGATIVE  a nonsense token -> {neg} -> {'PASS' if neg == 0 else '⛔ FAIL'}")
    plc = occurs(txt, "rubric") == pos
    print(f"  PLACEBO   run twice identical -> {'PASS' if plc else '⛔ FAIL'}")
    ctl = pos > 0 and g0 == 0 and neg == 0 and plc

    print(f"\n─── A · WHAT THE RELEASE'S OWN DOCUMENTATION NAMES (G3 — all nine) ───")
    rows = []
    for a in PUBLISHED + REMOVES3:
        n = occurs(txt, a)
        src = sorted(p.name for p in (ROOT / "corebench").glob("*.py")
                     if a.split("_k")[0] in p.read_text(errors="ignore"))[:3]
        rows.append({"arm": a, "in_card": n, "our_source": src})
        tag = ("⭐ NAMED by the release" if n else
               ("⛔ ABSENT from the card, GENERATED by our corebench" if src else
                "⛔ ABSENT from the card"))
        print(f"  {a:<16} card {n:>2}   {tag}")
        if src and not n: print(f"  {'':16} ours: {src}")
    named = sum(1 for r in rows if r["arm"] in PUBLISHED and r["in_card"])
    print(f"\n  ⭐ of R442's PUBLISHED_FIVE, named in the card : {named} of 5")
    print(f"  registered A 1 [1,2] -> {named}: "
          f"{'INSIDE' if 1 <= named <= 2 else '⛔ OUTSIDE'}, error {named-1:+d}")
    killed = named >= 3
    print(f"  pre-registered kill (card names >=3) -> "
          f"{'⭐ FIRES — PUBLISHED_FIVE is defensible' if killed else 'does not fire'}")

    print(f"\n─── B · WHAT THE CARD SAYS ABOUT THE CORE'S SIZE ───")
    m = re.search(r"up to (\w+)[^.]{0,200}?core rubric items", txt, re.I | re.S)
    dist = re.search(r"end up with (\w+) core rubric items \(about (\d+)%\)[^.]*?"
                     r"remainder having (\w+) or (\w+)", txt, re.I | re.S)
    W = {"one":1,"two":2,"three":3,"four":4,"five":5,"six":6}
    stated = bool(m or dist)
    modal = W.get(dist.group(1).lower()) if dist else (W.get(m.group(1).lower()) if m else None)
    print(f"  card states a size rule : {stated}")
    if m: print(f"    \"up to {m.group(1)}\" core rubric items")
    if dist:
        print(f"    ⭐ \"{dist.group(1)}\" for about {dist.group(2)}%, "
              f"remainder \"{dist.group(3)}\" or \"{dist.group(4)}\"")
    print(f"  registered B (card states it) -> {stated}: "
          f"{'HOLDS' if stated else '⛔ FAILS'}")
    print(f"  registered C modal 4 [2,6] -> {modal}: "
          f"{'INSIDE' if modal and 2 <= modal <= 6 else '⛔ OUTSIDE'}"
          f"{'' if modal is None else f', error {modal-4:+d}'}")
    dirn = bool(dist)
    print(f"  DIRECTIONAL the card gives a RANGE, not a single number -> "
          f"{'HOLDS' if dirn else '⛔ FAILS'}")

    print(f"\n─── VERDICT ───")
    if not ctl:
        world = "UNVERIFIED — a control did not fire; a zero from this grep is silence."
    elif killed:
        world = f"B GENUINELY PUBLISHED — the card names {named} of the five; no retraction."
    else:
        world = (f"⭐⭐⭐ A OUR CONSTRUCTIONS. The release's own documentation names **{named}** of "
                 f"R442's `PUBLISHED_FIVE` — `coval_core` — and none of the other four, which are "
                 f"generated by our own `corebench` source. ⛔ SO `published_five` IS RETRACTED AS A "
                 f"DESCRIPTION OF COVAL: the release ships ONE core. ⭐ AND R688's VERDICT SURVIVES "
                 f"FOR A BETTER REASON — the one core the release actually publishes IS in ③'s "
                 f"extension, so ③ does not exclude the released core at all. ⭐⭐ AND THIS IS §4's "
                 f"'the definition describes the instance' with the arithmetic showing: a definition "
                 f"tested against 'the published five' was tested against ONE released object and "
                 f"FOUR we built ourselves. ⚠ Plus the card STATES the core's size — "
                 f"{'about ' + dist.group(2) + '% have ' + dist.group(1) if dist else 'a rule'} — "
                 f"which is the object's own documentation answering the size question a k-sweep "
                 f"round was run to settle.")
    print(f"  {world}")

    sha = subprocess.run(["git","rev-parse","HEAD"],cwd=ROOT,capture_output=True,text=True).stdout.strip()
    print(f"\n  MULTIPLICITY: 9 arm names × (card search + provenance grep), 4 controls.")
    print(f"  ⭐ tree sha: {sha[:12]}")
    (HERE/"results").mkdir(exist_ok=True)
    (HERE/"results"/"release_says.json").write_text(json.dumps({
        "world": world, "controls_ok": ctl, "tree_sha": sha,
        "card": str(CARD.relative_to(ROOT)), "card_bytes": CARD.stat().st_size,
        "rows": rows, "n_published_named_in_card": named, "kill_fired": killed,
        "size_stated": stated, "modal_size": modal, "directional_holds": dirn,
        "registered": "A 1 [1,2]; B binary; C modal 4 [2,6]; kill if card names >=3",
        "check290": ("R688's NEXT cited R519.admitted for the four ③ removes -- that field is the "
                     "FIVE; the four are R404.admitted_2 minus admitted_2a. And it proposed reading "
                     "a release manifest that does not exist."),
        "wall_never_checked": ("R688's impossibility register said this 'needs the release's own "
                               "text'. data/DATASET_CARD.md has been on disk throughout."),
        "limit": ("absent from the card is not 'not published'; the load-bearing evidence is the "
                  "PAIR -- absent from the card AND generated by our own corebench source."),
    }, indent=2))
    print(f"  wrote {HERE/'results'/'release_says.json'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
