"""The provenance record already exists, in 22 rounds. Nothing has ever read it.

R343 closed by proposing a fix: "a round that writes the sha256 of its own source beside its
results, and a check that recomputes it, closes the direction measured here", and called it small.
It is smaller than that, because HALF OF IT IS ALREADY BUILT. `covalx/stamp.py` has existed for
some time, 22 rounds call `stamp(__file__)`, and its own docstring states the defect verbatim:

    "so an artifact cannot outlive the code that claims to have produced it"
    "a round patched after it ran passes that gate forever while its persisted numbers no longer
     exist in any output"

And `grep -rl source_sha256` over `assurance/`, `covalx/` and `db/` returns exactly one file:
`covalx/stamp.py` itself. The key is written by 22 rounds, mentioned by its own definition, and read
by NOTHING. It is not in the suite registry. So R343's next-gradient line was wrong about which half
was missing: the record was never the problem, the READER was, and I proposed building the half that
already existed.

ESTIMAND, named before the method
---------------------------------
Among rounds whose artifacts carry a source stamp AND whose source is established to hash ITSELF,
the number whose recorded hash does not equal the sha256 of the round's current `run.py` -- i.e.
artifacts that have outlived the code claiming to have produced them.

THREE-VALUED, and the third value is what a measured instrument looks like
--------------------------------------------------------------------------
  FRESH        recorded hash == sha256(run.py) today
  STALE        recorded hash != sha256(run.py) today, AND the round provably hashes its own source
  UNVERIFIED   an artifact carries a stamp-like key but this round cannot establish that the key
               holds a hash OF THAT SOURCE -- it may hash an input file, a dataset, a model. NEVER
               counted as STALE and never as FRESH.

⚠ AND THE THIRD BUCKET IS NOT DECORATION -- IT IS 24 ROUNDS AND IT ALREADY CAUGHT ME.
A first pass matched stamp-like KEY NAMES and reported 38 stale. A tighter pass, requiring the
source to visibly `sha256(Path(__file__).read_bytes())`, reported 14. realstat §4: when a loose and
a tight pattern disagree, the tight one is not "more conservative", it is the one that was tested.
But the tight one was ALSO wrong -- `R113_accuracy_matched_arm` self-hashes through
`**stamp(__file__)`, a helper in another file, which no regex over the round's own text can see. So
the instrument here resolves BOTH routes and reports what it cannot resolve as UNVERIFIED. The
instrument's unit is "a hash of this round's source"; the claim's unit is the same string, and they
were made equal before the controls were designed.

SCOPE
  population  every round with a run.py and at least one non-smoke json artifact -- a CENSUS
  instrument  sha256 of the committed run.py vs the hash recorded in the committed artifact
  baseline    the artifact and source as committed at this hash; nothing is executed
  regime      static; a round whose source was edited and whose artifact was regenerated is FRESH
              and is invisible here, which is correct -- it is not stale

WORLDS
  W1 THE RECORD IS KEPT CURRENT   ~0 stale. The stamp is maintained by habit even unenforced, and
                                  R343's hole is smaller than it looked.
  W2 THE RECORD ROTS             many stale. An unenforced record decays, and the fix R343 named is
                                  not "write it" but "read it" -- which is the state this repo is
                                  already in, with the writing done.

PREDICTION MATRIX, including a CROSS-INSTRUMENT row that can disagree
  W1 -> stale ~0;  and R344's execution census should find few artifacts that fail to regenerate
  W2 -> stale > 0; and every round R344 found byte-identical must come out FRESH here
  DISAGREE -> a round R344 regenerated byte-identically that this round calls STALE would mean one
              of the two instruments is wrong; the static one would be the suspect, because
              execution is the thing itself and a hash comparison is a proxy for it.

PRE-REGISTERED KILL
    if the planted controls fire in both directions and the known-stale real case is flagged:
        stale == 0  -> W1. The record is kept current without enforcement; say so.
        stale >= 1  -> W2. Name them. The remedy is a READER, and R343's proposal is retracted as
                       having named the wrong missing half.
    else:
        UNVERIFIED.

CONTROLS
  REAL POSITIVE   R307_a_size_matched_neutral_arm. Established STALE by EXECUTION, not by this
                  instrument: re-run in an isolated copy it regenerated its artifact with exactly
                  one field changed, `source_sha` dfa84b9ba7e4a4ff -> 4c946b228e592887, and
                  `git log` shows its source edited by d80e815 after the artifact was written. If
                  this static instrument does not flag it, the instrument is blind to the one case
                  whose answer is known from outside it.
  PLANTED         a synthetic round directory, stamped correctly (must be FRESH), then with its
                  source mutated by one byte (must be STALE). Both directions, because an
                  instrument that returns the same label on both measures nothing.
  g=0             no stamped rounds at all -> exit 2, never a clean bill.

⛔ ARITHMETIC TRAP: the count could be anything in [0, 22+]; it is a measurement. That `grep -rl
   source_sha256 assurance/` returns nothing is NOT -- it is a fact about the text, and it is
   reported as such.

EXIT
    0  controls hold and the census is reported
    1  a control misbehaved -- the count would be silence
    2  no stamped artifacts: an empty population, never a silent pass
"""
from __future__ import annotations

import ast
import hashlib
import json
import pathlib
import re
import shutil
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[3]
HERE = pathlib.Path(__file__).resolve().parent
STAMP_KEYS = re.compile(r"^(source_sha256|source_sha|src_sha|source_hash|src_hash|code_sha|"
                        r"run_sha|sha_source)$", re.I)
INLINE_SELFHASH = re.compile(r"sha256\(\s*(pathlib\.)?Path\(__file__\)[^)]*\.read_bytes\(\)|"
                             r"sha256\(\s*open\(__file__|__file__[^\n]*read_bytes\(\)\)\.hexdigest",
                             re.S)
KNOWN_STALE = "R307_a_size_matched_neutral_arm"


def self_hashes(src: str) -> tuple[bool, str]:
    """Both routes to a self-hash: inline, or through the shared helper. The helper route is why a
    regex over the round's own text is not enough -- `**stamp(__file__)` puts the sha256 call in
    covalx/stamp.py, where nothing about this round's text mentions hashing at all."""
    if re.search(r"stamp\(\s*__file__\s*\)", src):
        return True, "stamp(__file__)"
    if INLINE_SELFHASH.search(src):
        return True, "inline sha256(__file__)"
    return False, ""


def recorded_hashes(rd: pathlib.Path) -> list[tuple[str, str, str]]:
    out = []
    res = rd / "results"
    if not res.is_dir():
        return out
    for f in sorted(res.glob("*.json")):
        if "_smoke" in f.name or f.stat().st_size > 6_000_000:
            continue
        try:
            d = json.loads(f.read_text(encoding="utf-8"))
        except Exception:
            continue

        def walk(o, p=""):
            if isinstance(o, dict):
                for k, v in o.items():
                    if STAMP_KEYS.match(k) and isinstance(v, str) and re.fullmatch(r"[0-9a-f]{8,64}", v):
                        out.append((f.name, k, v))
                    else:
                        walk(v, f"{p}.{k}")
            elif isinstance(o, list):
                for i, v in enumerate(o[:200]):
                    walk(v, f"{p}[{i}]")
        walk(d)
    return out


def classify(rd: pathlib.Path):
    rp = rd / "run.py"
    if not rp.exists():
        return None
    rec = recorded_hashes(rd)
    if not rec:
        return None
    ok, how = self_hashes(rp.read_text(encoding="utf-8", errors="replace"))
    full = hashlib.sha256(rp.read_bytes()).hexdigest()
    if not ok:
        return ("UNVERIFIED", rec, full, "stamp-like key, but this round cannot establish it "
                                          "hashes THIS source")
    hit = any(full.startswith(v) for _f, _k, v in rec)
    return ("FRESH" if hit else "STALE", rec, full, how)


def planted_controls(tmp: pathlib.Path):
    """A synthetic round, stamped correctly then mutated by one byte. Both directions asserted."""
    d = tmp / "R000_plant"
    (d / "results").mkdir(parents=True, exist_ok=True)
    src = ("import hashlib, json, pathlib\n"
           "h = hashlib.sha256(pathlib.Path(__file__).read_bytes()).hexdigest()\n")
    (d / "run.py").write_text(src)
    h = hashlib.sha256((d / "run.py").read_bytes()).hexdigest()
    (d / "results" / "r.json").write_text(json.dumps({"source_sha256": h, "x": 1}))
    fresh = classify(d)
    (d / "run.py").write_text(src + "# one byte more\n")          # source edited, artifact stale
    stale = classify(d)
    ok = bool(fresh and fresh[0] == "FRESH" and stale and stale[0] == "STALE")
    return ok, (f"correct stamp -> {fresh[0] if fresh else None} (want FRESH); "
                f"source mutated -> {stale[0] if stale else None} (want STALE)")


def main() -> int:
    tmp = ROOT.parent / ".r345_scratch"
    shutil.rmtree(tmp, ignore_errors=True)
    tmp.mkdir(parents=True, exist_ok=True)
    p_ok, p_detail = planted_controls(tmp)
    shutil.rmtree(tmp, ignore_errors=True)
    print("R345 · the stamp nobody reads\n")
    print(f"  PLANTED CONTROL: {p_detail}  {'PASS' if p_ok else 'FAIL'}")

    # the fact about the text, reported as a fact and not as a measurement
    readers = subprocess.run(["grep", "-rl", "source_sha256", str(ROOT / "assurance"),
                              str(ROOT / "covalx"), str(ROOT / "db")],
                             capture_output=True, text=True).stdout.split()
    # __pycache__ holds a COMPILED COPY of stamp.py, not a reader of the key. Counting it would
    # inflate "who reads this" from one to two, and the whole point of the line is that it is one.
    readers = [pathlib.Path(r).relative_to(ROOT).as_posix() for r in readers
               if r and "__pycache__" not in r]
    print(f"  ⛔ FACT, not a measurement: files mentioning `source_sha256` anywhere in assurance/, "
          f"covalx/ or db/: {readers or '(none)'}")
    print("     The only one is the definition itself. The key is written by rounds and read by "
          "nothing.")

    rows = []
    for rp in sorted(ROOT.glob("E*/A*/R*/run.py")):
        c = classify(rp.parent)
        if c:
            rows.append({"round": rp.parent.name, "verdict": c[0],
                         "recorded": [v for _f, _k, v in c[1]][:2],
                         "current": c[2][:16], "how": c[3]})
    if not rows:
        print("\n  UNRUNNABLE: no artifact carries a source stamp. Exit 2, never 0.")
        return 2

    counts = {k: sum(1 for r in rows if r["verdict"] == k) for k in ("FRESH", "STALE", "UNVERIFIED")}
    print(f"\n  {len(rows)} round(s) carry a stamp-like key\n")
    for k in ("FRESH", "STALE", "UNVERIFIED"):
        print(f"    {k:<12}{counts[k]:>5}")

    known = next((r for r in rows if r["round"] == KNOWN_STALE), None)
    real_ok = bool(known and known["verdict"] == "STALE")
    print(f"\n  REAL POSITIVE ({KNOWN_STALE}) -- established STALE by EXECUTION, independently of")
    print(f"  this instrument: recorded {known['recorded'][0][:16] if known else '?'}, source now "
          f"{known['current'] if known else '?'}")
    print(f"  -> this instrument says {known['verdict'] if known else 'NOT FOUND'}  "
          f"{'PASS' if real_ok else 'FAIL'}")

    if counts["STALE"]:
        print(f"\n  STALE -- the artifact has outlived the code that claims to have produced it:\n")
        for r in [x for x in rows if x["verdict"] == "STALE"]:
            print(f"      {r['round']:<50} recorded {r['recorded'][0][:16]}  now {r['current']}"
                  f"   [{r['how']}]")
    if counts["UNVERIFIED"]:
        print(f"\n  UNVERIFIED ({counts['UNVERIFIED']}) -- a stamp-like key whose subject this round")
        print("  cannot establish. NOT counted stale, NOT counted fresh. A loose reading of these")
        print("  is what turned 14 into 38 on the first pass:")
        for r in [x for x in rows if x["verdict"] == "UNVERIFIED"][:8]:
            print(f"      {r['round']}")
        if counts["UNVERIFIED"] > 8:
            print(f"      … {counts['UNVERIFIED'] - 8} more")

    print()
    if not (p_ok and real_ok):
        print("  UNVERIFIED: a control misbehaved, so the counts above are silence.")
        verdict = "UNVERIFIED"
    elif counts["STALE"] == 0:
        print("  W1. Every resolvable stamp matches its source. The record is kept current even")
        print("  though nothing enforces it.")
        verdict = "W1_RECORD_CURRENT"
    else:
        print(f"  W2. {counts['STALE']} of {counts['FRESH'] + counts['STALE']} resolvable stamps are")
        print("  STALE. An unenforced record rots, and R343's closing proposal named the wrong")
        print("  missing half: the writing is done in 22 rounds and documented in covalx/stamp.py,")
        print("  whose docstring states this exact failure. What is missing is a READER.")
        verdict = "W2_RECORD_ROTS"

    art = {"rows": rows, "counts": counts, "readers_of_the_key": readers,
           "controls": {"planted": p_ok, "real_positive": real_ok},
           "verdict": verdict}
    outp = HERE / "results" / "r345_stamp_census.json"
    outp.write_text(json.dumps(art, indent=2, sort_keys=True))
    print(f"\n  artifact {outp.relative_to(ROOT)}  "
          f"sha256[:12] {hashlib.sha256(outp.read_bytes()).hexdigest()[:12]}")

    print("\n  ⚠ SCOPE. STALE means the artifact was not regenerated after its source changed. It")
    print("    does NOT mean the numbers are wrong -- an edit to a comment or a print statement")
    print("    changes the hash and nothing else. It means the artifact's currency is UNKNOWN, and")
    print("    the only instrument that settles it is re-running, which is R344's question.")
    print("    Nor does FRESH certify the artifact was produced by that source: whoever edits an")
    print("    artifact can write any hash into it. A stamp detects DRIFT, never FORGERY.")
    return 0 if (p_ok and real_ok) else 1


if __name__ == "__main__":
    sys.exit(main())
