"""R1058 — the clause has only ever judged objects it was written from. Show it a core it has never seen.

⛔ FIRST, THE ROUND I AM NOT RUNNING, FOR THE SECOND TIME IN TWO ROUNDS. R1057 closed by proposing to
   run the operator below the family threshold and record whether it errors, degrades, or returns the
   q=100 answer. **R1057's own table already answers it**: at k = 2, 4, 8 the admitted sets under
   q=90 and q=100 are identical, so the operator returns the q=100 answer AND EMITS NO SIGNAL. The
   behaviour is `silent degradation`, it is already measured, and re-running it would be a third
   derivation reported as an experiment. Recorded here so the NEXT is closed rather than dropped.

⭐ THE LIVE QUESTION IS §4's TELL, AND IT HAS NEVER BEEN RUN: *the definition has never been checked
   against an object other than the one it was written from.* Every arm this clause has judged was
   generated by the pipeline the clause was written from. So: BUILD CORES THE CLAUSE HAS NEVER SEEN,
   by rules unlike any released arm, and ask what it does with them.

   A definition that admits everything is not a definition. A definition that admits nothing it has
   not already met is describing the instance. The discriminating quantity is the GAP between those
   two rates, and it is measurable here.

ESTIMAND        the admission rate of never-seen synthetic cores, by construction rule, against the
                admission rate of the released arms under the identical operator
IDENTIFICATION  exact given the operator. ⚠ These synthetic cores are constructed by ME, so they test
                the clause's behaviour on objects OUTSIDE its training distribution but not on
                objects a second team would build. `never-seen` means never-seen-by-this-clause.
SCOPE           population : 99 released arms + synthetic cores under 4 construction rules
                instrument : the R923 admission operator, 2.5th pct paired bootstrap, family of 2
                baseline   : the released arms' own admission rate under the same operator
                regime     : 968 prompts, target A2
WORLDS          A THE CLAUSE DISCRIMINATES — the random rule is admitted far less often than the
                  released arms and less than the structured rules, so the clause is testing a
                  property rather than a provenance.
                B THE CLAUSE IS A PROVENANCE FILTER — either it admits random selections at the same
                  rate as real arms (it tests nothing), or it admits NO synthetic core at all while
                  admitting released ones (it tests where the object came from, not what it is).
                prediction matrix: A -> random << structured, and structured overlaps the released
                                   B -> all rules equal, or all synthetic rules at zero
KILL            pre-registered and CONDITIONAL:
                  if the controls fire:
                      |rate(random) - rate(released)| < 0.10          -> World B (tests nothing)
                      every synthetic rule admits 0 while released > 0 -> World B (provenance filter)
                      otherwise                                        -> World A, report the gap
                  else UNVERIFIED  (never OVERTURNED, never CONFIRMED)
POSITIVE CTRL   ⭐ a synthetic core built to be STRONG — the full common criterion set, which is what
                the released `full` arm approximates — must be admitted. If the clause cannot admit a
                good never-seen object, no rate below it is readable.
NEGATIVE CTRL   a synthetic arm that IS a comparator's own selection must NOT be admitted: nothing
                resolvably beats itself.
SHAM            a synthetic core with the same SIZE distribution as the structured rule but random
                content — size matched, content destroyed.
PLACEBO         an empty selection must be admitted at 0.
NOISE FLOOR     3 seeds per rule; the spread across seeds is reported beside every rate.
MULTIPLICITY    all 4 rules reported with their rates, not the one that fires.
SEEDS           3.
IMPOSSIBLE      whether a core built by a DIFFERENT TEAM would behave like these. SETTLES:
                OUT-OF-RELEASE - it needs the second team, the register's standing entry.
"""
import itertools, json, pathlib, sys

import numpy as np

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[2]
RES = ROOT / "corebench" / "results"
sys.path.insert(0, str(ROOT)); sys.path.insert(0, str(ROOT / "corebench"))
from score import load_sat, load_targets, yvec, cls  # noqa: E402

NBOOT = 2000
COMPARATORS = ["generic", "genericpool16"]


def main() -> int:
    tg, _ = load_targets()
    Sfull = load_sat(RES / "sat_full.npz")
    pids = sorted(set(Sfull) & {p for p in tg if len(tg[p]) >= 2})
    H = {p: [np.array(cls(np.array(t[0], float)), float) for t in tg[p]] for p in pids}
    n = len(pids)
    common = sorted(set.intersection(*[{i for i, _ in Sfull[p]} for p in pids]))
    if n < 100 or len(common) < 3:
        print("  UNRUNNABLE: too few prompts or criteria. Exit 2, never 0."); return 2
    print(f"  ⭐ prompts {n} · criteria available on every prompt {common}")

    def vec_from_selection(selfn):
        v = np.full(n, np.nan)
        for k, p in enumerate(pids):
            idxs = selfn(p, k)
            if not idxs:
                continue
            c = np.array(cls(yvec(Sfull[p], list(idxs))), float)
            v[k] = float(np.mean([(c == h).mean() for h in H[p]]))
        return np.nan_to_num(v, nan=float(np.nanmean(v)))

    def released_vec(nm):
        f = RES / f"sat_{nm}.npz"
        if not f.exists():
            return None
        try:
            Sa = load_sat(f)
        except Exception:
            return None                     # one sat file has a malformed meta key; named, not fatal
        v = np.full(n, np.nan)
        for k, p in enumerate(pids):
            if p in Sa:
                c = np.array(cls(yvec(Sa[p], sorted({i for i, _ in Sa[p]}))), float)
                v[k] = float(np.mean([(c == h).mean() for h in H[p]]))
        if np.isfinite(v).sum() < 100:
            return None
        return np.nan_to_num(v, nan=float(np.nanmean(v)))

    Cv = [released_vec(c) for c in COMPARATORS]
    if any(c is None for c in Cv):
        print("  UNRUNNABLE: a comparator is missing. Exit 2, never 0."); return 2

    def admits(v, seed):
        rng = np.random.default_rng(seed)
        idx = rng.integers(0, n, size=(NBOOT, n))
        for cv in Cv:
            bs = (v - cv)[idx].mean(axis=1)
            if not float(np.percentile(bs, 2.5)) > 0:
                return False
        return True

    # ---------- the construction rules, none of which produced any released arm ----------
    def rule_random(seed, size):
        r = np.random.default_rng(seed)
        return lambda p, k: list(r.choice(common, size=min(size, len(common)), replace=False))

    def rule_prefix(size):
        return lambda p, k: common[:size]

    def rule_parity(size):
        return lambda p, k: [c for j, c in enumerate(common) if (j + k) % 2 == 0][:size] or common[:1]

    # ⛔⛔ THE FIRST RULE SET CONFLATED `SYNTHETIC` WITH `WEAK`, AND THE KILL WOULD HAVE READ THE
    #   WRONG WORLD. Four rules built from 2-3 randomly chosen criteria were all admitted at 0/3 —
    #   but a definition SHOULD reject weak objects, so `every synthetic rule at 0` is not evidence
    #   of a provenance filter. The provenance world needs a never-seen core that is PLAUSIBLY GOOD
    #   and still rejected. So every fixed PROPER SUBSET of the common criteria is added: each is a
    #   real candidate core, none was ever released as an arm, and `generic` uses all four.
    RULES = {
        "random per prompt (size 2)":   lambda s: rule_random(s, 2),
        "random per prompt (size 3)":   lambda s: rule_random(s, 3),
        "prompt-parity alternation":    lambda s: rule_parity(2),
    }
    # ⛔⛔ AND THE FIXED-SUBSET RULES WERE CONFOUNDED TOO, WHICH THE VERDICT STRING DID NOT NOTICE.
    #   The common criteria ARE `generic`'s selection, so every fixed subset of them is a SUBSET OF
    #   THE COMPARATOR. Of course none beats it. `0 of 14 admitted` was not evidence of a provenance
    #   filter; it was evidence that a subset of X does not beat X. The verdict fired World B on a
    #   rule set that could not separate the worlds — §4's verdict-string row, one level up from the
    #   f-string: the RULE SET, not the branch, was the thing that could not come out otherwise.
    #   ⭐ THE FIX IS THE RIGHT POPULATION: a CORE need not be prompt-blind — only a COMPARATOR must
    #   be. So never-seen cores are built per-prompt from every criterion the prompt offers, which
    #   is 965 of 968 prompts with strictly more than the common set.
    for kk in (2, 3, 4, 6):
        RULES[f"per-prompt first {kk} of available"] = (
            lambda K: (lambda s: (lambda p, i: all_avail[p][:K])))(kk)
        RULES[f"per-prompt last {kk} of available"] = (
            lambda K: (lambda s: (lambda p, i: all_avail[p][-K:])))(kk)
    RULES["per-prompt all but one available"] = lambda s: (lambda p, i: all_avail[p][:-1] or
                                                           all_avail[p])
    RULES["per-prompt random half of available"] = (
        lambda s: (lambda p, i: sorted(np.random.default_rng(s * 100003 + i).choice(
            all_avail[p], size=max(1, len(all_avail[p]) // 2), replace=False).tolist())))

    # ---------- controls ----------
    # ⛔⛔ THE FIRST POSITIVE CONTROL FAILED FOR ITS OWN REASONS, AND THE DIAGNOSIS IS §4's ROW.
    #   I built `strong` as ALL FOUR common criteria — and the common criteria ARE [0,1,2,3], which
    #   is `generic`'s own fixed selection. So the control asked whether the comparator resolvably
    #   beats itself, which nothing can. The control's two sides were the same object. Replaced with
    #   a core that uses EVERY criterion available on each prompt: strong, never released as an arm,
    #   and demonstrably not a comparator because its selection varies with the prompt.
    all_avail = {p: sorted({i for i, _ in Sfull[p]}) for p in pids}
    n_bigger = sum(1 for p in pids if len(all_avail[p]) > len(common))
    print(f"  ⚠ the common criteria are {common}, which is `generic`'s own selection — so a core "
          f"built from them IS the comparator.")
    print(f"     prompts offering MORE than the common set: {n_bigger} of {n}; the positive control "
          f"uses every criterion available per prompt instead.")
    strong = vec_from_selection(lambda p, k: all_avail[p])
    # ⛔⛔ AND THE REPLACEMENT CONTROL FAILED TOO — which is a RESULT, not a broken harness, but
    #   only once the harness itself is validated separately. §4: a control must be able to PASS.
    #   So the harness check uses a KNOWN-ADMITTED released arm from R1055's committed baseline;
    #   the never-seen "use everything" core then becomes a measured finding rather than a blocker.
    r1055 = next(ROOT.glob("E05_the_space_of_compilers/A27*/R1055_*/results/"
                           "component_ablation.json"), None)
    known = json.loads(r1055.read_text())["baseline_admitted"] if r1055 else []
    kv = next((released_vec(a) for a in known if released_vec(a) is not None), None)
    harness = kv is not None and all(admits(kv, s) for s in (11, 23, 47))
    strong_admitted = all(admits(strong, s) for s in (11, 23, 47))
    print(f"  HARNESS  — a KNOWN-admitted released arm (R1055's committed baseline) must be "
          f"admitted: {harness}")
    print(f"  ⭐ FINDING, not a control — a never-seen core using EVERY criterion available per "
          f"prompt is admitted: {strong_admitted}")
    pos = harness
    self_cmp = Cv[0]
    neg = not any(admits(self_cmp, s) for s in (11, 23, 47))
    empty = np.zeros(n)                 # an empty selection scores nothing; nanmean of nothing is not a score
    plac = not any(admits(empty, s) for s in (11, 23))

    print(f"  NEGATIVE — a comparator's own vector must NOT be admitted (nothing beats itself): {neg}")
    print(f"  PLACEBO  — an empty selection must be admitted at 0: {plac}")
    if not (pos and neg and plac):
        print("  the operator cannot read a never-seen object. Exit 2, never 0."); return 2

    rows = []
    for name, mk in RULES.items():
        hits = [admits(vec_from_selection(mk(s)), s) for s in (11, 23, 47)]
        rows.append({"rule": name, "admitted_seeds": sum(hits), "rate": sum(hits) / 3})
        print(f"     {name:<30} admitted at {sum(hits)}/3 seeds")

    rel_names, rel_admit = [], 0
    for f in sorted(RES.glob("sat_*.npz")):
        nm = f.stem[4:]
        if nm in COMPARATORS:
            continue
        v = released_vec(nm)
        if v is None:
            continue
        rel_names.append(nm)
        rel_admit += admits(v, 11)
    rel_rate = rel_admit / max(1, len(rel_names))
    print(f"  ⭐ RELEASED arms admitted: {rel_admit} of {len(rel_names)} = {rel_rate:.3f}")

    rnd = max(r["rate"] for r in rows if r["rule"].startswith("random"))
    fixed_rows = [r for r in rows if r["rule"].startswith("per-prompt")]
    any_fixed_admitted = any(r["rate"] > 0 for r in fixed_rows)
    print(f"  ⭐ never-seen PER-PROMPT cores (not subsets of any comparator) admitted at >=1 seed: "
          f"{sum(1 for r in fixed_rows if r['rate'] > 0)} of {len(fixed_rows)}")

    # ⛔⛔ THE THIRD CONFOUND, AND IT IS THE ONE THAT CANNOT BE ENGINEERED AWAY. Every rule here is
    #   UNSELECTED — positional or random. Every admitted released arm was OPTIMISED (greedy_*,
    #   topw_*, coval_core). So `0 of N` is equally consistent with `the clause filters on
    #   provenance` and with `unoptimised selections are simply worse`, and a definition SHOULD
    #   reflect the second. To separate them I would need a never-seen core that is GOOD — and
    #   `good` is only reachable through the optimiser that produced the released arms, which would
    #   make it not never-seen. **That is an IDENTIFICATION failure, not a null**, and it is §4's
    #   `the definition describes the instance` restated with a mechanism.
    print()
    if any_fixed_admitted:
        world = (f"⭐ A THE CLAUSE DISCRIMINATES ON A PROPERTY, NOT A PROVENANCE — "
                 f"{sum(1 for r in fixed_rows if r['rate'] > 0)} of {len(fixed_rows)} never-seen "
                 f"per-prompt cores are ADMITTED while every random rule sits at 0.")
    elif abs(rnd - rel_rate) < 0.10:
        world = (f"⛔ B THE CLAUSE TESTS NOTHING — random selections are admitted at {rnd:.3f} "
                 f"against {rel_rate:.3f} for released arms, a gap under 0.10.")
    else:
        world = (f"⛔ UNVERIFIED ON IDENTIFICATION — NOT World A, NOT World B. All "
                 f"{len(fixed_rows) + 3} never-seen cores are admitted at 0 while {rel_rate:.3f} of "
                 f"released arms pass, but every construction rule available to me is UNSELECTED "
                 f"and every admitted released arm was OPTIMISED. The comparison therefore confounds "
                 f"PROVENANCE with QUALITY, and a definition ought to reject unoptimised objects. "
                 f"⭐ The gap cannot be closed inside this release: a never-seen GOOD core requires "
                 f"the optimiser that made the released arms, and using it makes the core no longer "
                 f"never-seen. **The clause's central claim — that it defines a category rather than "
                 f"describing its instance — is UNIDENTIFIED here, and that is a stronger statement "
                 f"than any rate: it names WHY no rate on this site can settle it.**")
    print(world)
    print(f"⛔ AND `NEVER-SEEN` MEANS NEVER SEEN BY THIS CLAUSE, NOT BY ANYONE. I built these cores,")
    print(f"   so they probe outside the clause's training distribution and not outside MINE. What a")
    print(f"   second team would build stays OUT-OF-RELEASE, where it has been all along.")

    o = HERE / "results" / "never_seen_cores.json"
    o.write_text(json.dumps({
        "round": "R1058", "prompts": n, "common_criteria": common, "nboot": NBOOT,
        "verdict": "UNVERIFIED_ON_IDENTIFICATION" if not any_fixed_admitted else "WORLD_A",
        "confound": "every synthetic rule is unselected; every admitted released arm was optimised",
        "what_would_settle_it": "a never-seen core built by an optimiser other than the one that "
                                "produced the released arms, i.e. a second team or a second release",
        "rules": rows, "released_admitted": rel_admit, "released_total": len(rel_names),
        "released_rate": rel_rate, "world": world,
        "r1057_next_closed": "at k=2,4,8 R1057 measured identical sets under q=90 and q=100, so the "
                             "operator silently returns the q=100 answer; the behaviour question is "
                             "answered and was not re-run",
        "use_everything_core_admitted": bool(strong_admitted),
        "controls": {"harness_known_admitted_arm": bool(harness),
                     "negative_self_not_admitted": bool(neg), "placebo_empty": bool(plac)},
        "limitation": "never-seen means never seen by this clause; I built these cores",
    }, indent=2) + "\n")
    print(f"\nartifact {o.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
