#!/usr/bin/env python3
"""R775 · four disjoint families — is the prompt component real, or an artifact of similar RULES?

⛔ CHECK #377: R774's REGISTERED THIRD FAMILY CARRIED A BIGGER CONFOUND THAN THE ONE IT NAMED.
   Three of its five members are TARGET-READING (`greedy_k`, `indep_k`, `oracle_k` — R760's rule off
   `select_core.py:102`), so their differences are generated by how much of the label each read, not
   by a different selector rule. And `generic` is the comparator itself (R765). ⭐ The release
   supports a cleaner design: 86 arms have full coverage (6 named, 17 target-reading, 63 selector),
   and FOUR families of five exist with **zero shared OBJECTS** under R730's partition, no `_08b`
   foreign judge and no `_ctl`/`_det` replicas — giving six pairs that separate SELECTOR-SELECTOR
   from SELECTOR-TARGETREADER.

⛔ FORCED, LABELLED:
  D1 raw correlations across pairs are not comparable — each pair has its own attenuation ceiling.
     Every number is divided by its OWN ceiling.
  D2 the families differ in A2 LEVEL by construction (target-readers ~0.61, selectors ~0.49). Printed,
     not treated as a finding.
  D3 six correlations from four families are NOT six independent numbers — each family is in three
     pairs. The axis null is therefore GENERATED by permuting family labels, not assumed.

CONTROLS  DISJOINT at the OBJECT level (exit 2) · POSITIVE (a planted prompt-scale must raise ALL six,
          swept) · g=0 · NEGATIVE (200 one-sided permutations) · SHAM (each family split into
          overlapping halves — what sharing alone buys) · PLACEBO (a family against itself = 1.0) ·
          CONFOUND (each family's internal scale, so a compressed family is visible).
UNIT      prompt · arm pair within a family · FAMILY PAIR. D3: not six independent observations.
"""
import itertools, json, math, pathlib, subprocess, sys

import numpy as np

ROOT = pathlib.Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT / "corebench"))
from score import load_sat, load_targets, cls          # noqa: E402

RES = ROOT / "corebench/results"
A24 = ROOT / "E05_the_space_of_compilers/A24_what_the_definition_costs"
L = "ABCD"
PR = list(itertools.combinations(range(4), 2))
NDRAW = 200
FAM = {
    "F1_committed":       ["coval_core", "topw_k3", "topw_k4", "topw_k6", "topw_k8"],
    "F2_selector_seed":   ["random_k4_s0", "random_k4_s1", "random_k4_s2", "topabs_k4", "topvar_k4"],
    "F3_target_reading":  ["oracle_k4", "oracle_k4_fit1", "greedy_k4_fit1", "indep_k4_fit1",
                           "greedy_k4_greedy_kA"],
    "F4_selector_ksweep": ["random_k2_s0", "random_k3_s0", "random_k6_s0", "random_k8_s0",
                           "random_k12_s0"],
}
TARGET_FAM = {"F3_target_reading"}


def _plain(o):
    if isinstance(o, np.bool_):    return bool(o)
    if isinstance(o, np.integer):  return int(o)
    if isinstance(o, np.floating): return float(o)
    if isinstance(o, np.ndarray):  return o.tolist()
    raise TypeError(type(o))


def main():
    # ---- CONTROL · DISJOINT at the OBJECT level ------------------------------------------------
    r730 = json.loads((A24 / "R730_seven_tags_are_not_seven_objects/results/"
                       "r730_object_partition.json").read_text())
    obj = {}
    for g in r730["multi_tag_classes"]:
        for t in g: obj[t] = sorted(g)[0]
    O = {n: {obj.get(t, t) for t in f} for n, f in FAM.items()}
    bad = [(a, b, O[a] & O[b]) for a, b in itertools.combinations(FAM, 2) if O[a] & O[b]]
    if bad:
        print(f"UNRUNNABLE: families share objects {bad}. Exit 2, never 0."); return 2
    for n, f in FAM.items():
        assert len(O[n]) == 5 and not any(m in t for t in f for m in ("_08b", "_ctl", "_det"))
    print(f"  DISJOINT    4 families x 5 arms, 0 shared OBJECTS under R730, no foreign judge, "
          f"no replicas  PASS")

    targets, _ = load_targets()
    POOL = load_sat(RES / "sat_genericpool16.npz")
    base = load_sat(RES / "sat_random_k4_s0.npz")
    pids = sorted({p for p in base if p in targets and p in POOL and len(targets[p]) >= 2})
    P = len(pids)
    HC = [np.array([cls(y) for y, _ in targets[p]]) for p in pids]

    def a2(tag):
        S = load_sat(RES / f"sat_{tag}.npz")
        o = np.zeros(P)
        for ai, p in enumerate(pids):
            ii = sorted({i for i, _ in S[p]})
            Y = np.array([sum(S[p].get((i, x), 0.0) for i in ii) for x in L])
            s = np.sign(Y[[i for i, _ in PR]] - Y[[j for _, j in PR]])
            o[ai] = np.mean([(s == h).mean() for h in HC[ai]])
        return o

    A = {t: a2(t) for f in FAM.values() for t in f}

    def mags(fam):
        return np.abs(np.array([A[a] - A[b] for a, b in itertools.combinations(FAM[fam], 2)]))

    M = {n: mags(n) for n in FAM}
    C = {n: M[n].mean(0) for n in FAM}
    print(f"\n  ⚠ CONFOUND (D2)  per family: mean A2 · internal mean |d| · scale median")
    for n in FAM:
        print(f"     {n:<22}{np.mean([A[t].mean() for t in FAM[n]]):>8.4f}"
              f"{M[n].mean():>12.4f}{np.median(C[n]):>10.4f}")
    minint = min(M[n].mean() for n in FAM)
    f3_compressed = M["F3_target_reading"].mean() < 0.5 * np.median(
        [M[n].mean() for n in FAM if n != "F3_target_reading"])

    # ---- E1 · reliabilities and per-pair ceilings ----------------------------------------------
    rng = np.random.default_rng(775)

    def rel(n):
        Mm, k = M[n], M[n].shape[0]
        rs = []
        for _ in range(NDRAW):
            idx = rng.permutation(k)
            h1, h2 = Mm[idx[:k // 2]].mean(0), Mm[idx[k // 2:]].mean(0)
            if h1.std() > 0 and h2.std() > 0:
                r = float(np.corrcoef(h1, h2)[0, 1])
                rs.append(2 * r / (1 + r) if r > -1 else 0.0)
        return float(np.mean(rs))
    R = {n: rel(n) for n in FAM}
    print(f"\n  ⭐ E1 · split-half reliability: " + "  ".join(f"{n[:2]} {R[n]:.4f}" for n in FAM))

    # ---- E2 · the six correlations, each against its OWN ceiling --------------------------------
    negd = [float(np.corrcoef(C["F1_committed"], C["F2_selector_seed"][rng.permutation(P)])[0, 1])
            for _ in range(NDRAW)]
    nhi = float(np.percentile(negd, 97.5))
    print(f"\n  ⭐ E2 · SIX CROSS-FAMILY CORRELATIONS, each against its OWN ceiling (D1)")
    print(f"  {'pair':<42}{'raw':>9}{'ceiling':>10}{'relative':>10}   class")
    rows = {}
    for a, b in itertools.combinations(FAM, 2):
        raw = float(np.corrcoef(C[a], C[b])[0, 1])
        ceil = math.sqrt(max(R[a], 0) * max(R[b], 0))
        klass = "sel-TARGET" if (a in TARGET_FAM) != (b in TARGET_FAM) else "sel-sel"
        rows[f"{a} x {b}"] = {"raw": raw, "ceiling": ceil, "rel": raw / max(ceil, 1e-12),
                              "class": klass}
        print(f"  {a+' x '+b:<42}{raw:>9.4f}{ceil:>10.4f}{raw/max(ceil,1e-12):>10.4f}   {klass}")
    ss = [v["rel"] for v in rows.values() if v["class"] == "sel-sel"]
    st = [v["rel"] for v in rows.values() if v["class"] == "sel-TARGET"]
    diff = float(np.mean(ss) - np.mean(st))
    print(f"\n  ⭐ E3 · selector-selector mean {np.mean(ss):.4f} (n={len(ss)})   "
          f"selector-TARGET mean {np.mean(st):.4f} (n={len(st)})   difference {diff:+.4f}")

    # ---- D3 · the axis null, GENERATED by permuting family labels ------------------------------
    names = list(FAM)
    perm = []
    for _ in range(NDRAW):
        lab = set(rng.choice(names, 1, replace=False))
        s1 = [rows[k]["rel"] for k in rows
              if (k.split(" x ")[0] in lab) != (k.split(" x ")[1] in lab)]
        s2 = [rows[k]["rel"] for k in rows
              if (k.split(" x ")[0] in lab) == (k.split(" x ")[1] in lab)]
        if s1 and s2: perm.append(float(np.mean(s2) - np.mean(s1)))
    plo, phi = np.percentile(perm, 2.5), np.percentile(perm, 97.5)
    print(f"  D3 NULL     permuting WHICH family is labelled target-reading, {len(perm)} draws: "
          f"{np.mean(perm):+.4f} [{plo:+.4f}, {phi:+.4f}]   observed {diff:+.4f}")

    # ---- CONTROLS -------------------------------------------------------------------------------
    plc = float(np.corrcoef(C["F1_committed"], C["F1_committed"])[0, 1])
    print(f"\n  PLACEBO     a family against ITSELF: {plc:.6f}  "
          f"{'PASS' if abs(plc-1) < 1e-9 else '⛔ FAIL'}")
    print(f"  NEGATIVE    {NDRAW} one-sided permutations: {np.mean(negd):+.4f} "
          f"[{np.percentile(negd,2.5):+.4f}, {nhi:+.4f}]")
    print(f"  SHAM        each family split into OVERLAPPING halves (what sharing alone buys):")
    shamv = {}
    for n in FAM:
        prs = list(itertools.combinations(FAM[n], 2))
        anchor = FAM[n][0]
        ha = M[n][[i for i, p_ in enumerate(prs) if anchor in p_]].mean(0)
        hb = M[n][[i for i, p_ in enumerate(prs) if anchor not in p_]].mean(0)
        shamv[n] = float(np.corrcoef(ha, hb)[0, 1])
        print(f"     {n:<22}{shamv[n]:+.4f}")
    dose = {}
    v = {t: float(np.var(A[t])) for t in A}
    for w in (0.0, 0.25, 0.5, 1.0):
        s = rng.lognormal(0, w, P) if w > 0 else np.ones(P)
        Asim = {t: rng.normal(0, math.sqrt(max(v[t], 1e-12)), P) * s for t in A}
        Cs = {n: np.abs(np.array([Asim[a] - Asim[b]
                                  for a, b in itertools.combinations(FAM[n], 2)])).mean(0)
              for n in FAM}
        cs = [float(np.corrcoef(Cs[a], Cs[b])[0, 1]) for a, b in itertools.combinations(FAM, 2)]
        dose[w] = {"min": float(min(cs)), "mean": float(np.mean(cs)),
                   "all_detected": bool(min(cs) > nhi)}
        print(f"  POSITIVE    planted width {w:>4.2f} -> six correlations min {min(cs):+.4f} "
              f"mean {np.mean(cs):+.4f}   ALL detected {min(cs) > nhi}")
    pos = dose[1.0]["all_detected"]
    g0 = not dose[0.0]["all_detected"]
    mono = all(dose[a]["mean"] <= dose[b]["mean"] + 1e-9
               for a, b in zip([0.0, 0.25, 0.5], [0.25, 0.5, 1.0]))
    print(f"              registered band — 0.00 must NOT detect all, 1.00 must: {pos and g0}  "
          f"{'PASS' if pos and g0 else '⛔ FAIL'}   monotone: {mono}")

    ctrl = pos and g0 and abs(plc - 1) < 1e-9
    if not ctrl:
        world = "UNVERIFIED"
    elif f3_compressed:
        world = (f"C · the target-reading family is COMPRESSED — internal |d| {M['F3_target_reading'].mean():.4f} "
                 f"below half the others'")
    elif diff > phi:
        world = (f"B · RULE ARTIFACT — selector-selector exceeds cross-class by {diff:+.4f}, above the "
                 f"permutation 97.5th of {phi:+.4f}")
    elif plo <= diff <= phi:
        world = (f"A · CLASS-INDEPENDENT — the difference {diff:+.4f} sits inside the permutation "
                 f"interval [{plo:+.4f}, {phi:+.4f}]; the prompt component survives the axis")
    else:
        world = f"NO WORLD — difference {diff:+.4f} below the permutation interval"
    print(f"\n  WORLD {world}")

    out = pathlib.Path(__file__).parent / "results/four_families.json"
    out.write_text(json.dumps({
        "tree_sha": subprocess.run(["git", "rev-parse", "HEAD^{tree}"], cwd=ROOT,
                                   capture_output=True, text=True).stdout.strip()[:16],
        "n_prompts": P, "families": FAM,
        "family_mean_a2": {n: float(np.mean([A[t].mean() for t in FAM[n]])) for n in FAM},
        "family_internal_absd": {n: float(M[n].mean()) for n in FAM},
        "reliability": R, "pairs": rows,
        "sel_sel_mean": float(np.mean(ss)), "sel_target_mean": float(np.mean(st)),
        "difference": diff, "perm_lo": float(plo), "perm_hi": float(phi),
        "sham_within_family": shamv, "negative_hi": nhi,
        "dose": {str(k): val for k, val in dose.items()},
        "controls": {"placebo": plc, "positive": bool(pos), "g0": bool(g0), "monotone": bool(mono),
                     "f3_compressed": bool(f3_compressed)},
        "world": world,
    }, indent=2, default=_plain))
    print(f"  artifact -> {out.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
