#!/usr/bin/env python3
"""assurance/generate_round_index.py — give every round a home in its arc's README.

WHY. `every_round_reaches_the_readme.py` flags **273 of 305** rounds, and its own sentence is the
argument: *"a round that ran and is never mentioned is a result nobody has."* Measured coverage
before this ran:

    root README.md (an EPOCH summary since 2026-08-02)   29 / 305   10%
    all arc READMEs combined                             66 / 305   22%
    root + arcs                                          94 / 305   31%
    root + arcs + FORMULATION.md                        107 / 305   35%

So it is not a check-targeting bug — pointing the check at the arc READMEs instead would have
moved 10% to 22% and still failed. **The index was never built.** P16 says the arc README is a
table of contents for its rounds, so that is where this writes.

DESIGN, and every choice is a defence against a failure this project has already made:

  * **A DELIMITED BLOCK, never a rewrite.** Everything between the two markers is regenerated;
    everything else is untouched. L81 — annotate, do not rewrite. An arc's prose is the part a
    human wrote and it is the part a generator must not be able to reach.
  * **REGENERABLE, so it cannot go stale.** `A16`'s hand-written count was wrong in three places
    at once and the file it was in *contains the warning about that exact failure*. A number that
    is re-derived from the tree on demand cannot drift from it.
  * **THE SOURCE OF EVERY LINE IS DECLARED.** A description comes from the round's README heading,
    else its `run.py` docstring, else the directory slug. The fallback is the weakest and it is
    LABELLED in the output, because a generated table that silently prettifies a slug reads
    exactly like one somebody wrote.
  * **NO SILENT BLANKS.** A round with no readable description is listed with `—` and counted in
    the summary, never dropped from the table.

ESTIMAND      per arc: every round directory appears in exactly one row of its arc's index.
              Globally: the coverage fraction, before and after.
IDENTIFICATION exact — the tree is the population and the table is a rendering of it.
POSITIVE CTRL a round hidden from the tree must DISAPPEAR from the regenerated index, and
              `every_round_reaches_the_readme` must flag it. Fails at g=0: with nothing hidden the
              same check must not flag it.
NEGATIVE CTRL prose outside the markers must be byte-identical after regeneration.
IMPOSSIBLE    whether a description is ACCURATE. This copies what the round says about itself; it
              cannot know whether the round's own heading is a fair summary of what it did.
"""
from __future__ import annotations
import argparse, hashlib, json, pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
BEGIN = "<!-- ROUND-INDEX:BEGIN — generated by assurance/generate_round_index.py, do not hand-edit -->"
END = "<!-- ROUND-INDEX:END -->"
BLOCK = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)


def describe(rd: pathlib.Path) -> tuple[str, str]:
    """(one-line description, WHERE IT CAME FROM). The source is returned so a fallback is visible."""
    rm = rd / "README.md"
    if rm.exists():
        for ln in rm.read_text(errors="ignore").split("\n"):
            ln = ln.strip()
            if ln.startswith("#"):
                t = re.sub(r"^#+\s*", "", ln)
                t = re.sub(r"^R\d+\s*[—:-]\s*", "", t).strip()
                if t:
                    return t, "README"
    rp = rd / "run.py"
    if rp.exists():
        m = re.search(r'^\s*(?:"""|\'\'\')(.*)', rp.read_text(errors="ignore"), re.M)
        if m:
            t = re.sub(r"^R\d+\s*[—:-]\s*", "", m.group(1).strip()).strip()
            if t:
                return (t[:150] + "…") if len(t) > 150 else t, "docstring"
    return rd.name.split("_", 1)[1].replace("_", " ") if "_" in rd.name else "—", "SLUG (fallback)"


def coverage() -> tuple[int, int]:
    rounds = {p.name.split("_")[0] for p in ROOT.glob("E0*/A*/R*") if p.is_dir()}
    txt = (ROOT / "README.md").read_text(errors="ignore")
    txt += "\n".join(p.read_text(errors="ignore") for p in ROOT.glob("E0*/A*/README.md"))
    f = ROOT / "E05_the_space_of_compilers" / "FORMULATION.md"
    if f.exists():
        txt += f.read_text(errors="ignore")
    hit = sum(1 for r in rounds
              if re.search(rf"\b{r}\b", txt) or re.search(rf"\br{int(r[1:])}\b", txt))
    return hit, len(rounds)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true")
    a = ap.parse_args()

    before = coverage()
    arcs = sorted(p for p in ROOT.glob("E0*/A*") if p.is_dir())
    created, updated, fallbacks, total_rows = [], [], [], 0
    print(f"  coverage BEFORE: {before[0]}/{before[1]}  ({before[0]/before[1]:.0%})\n")
    print(f"  {'arc':<54}{'rounds':>7}{'created?':>10}  descriptions from")

    for arc in arcs:
        rds = sorted((p for p in arc.glob("R*") if p.is_dir()),
                     key=lambda p: int(re.sub(r"\D", "", p.name.split("_")[0]) or 0))
        if not rds:
            continue
        rows, srcs = [], {}
        for rd in rds:
            rid = rd.name.split("_")[0]
            desc, src = describe(rd)
            srcs[src] = srcs.get(src, 0) + 1
            if src.startswith("SLUG"):
                fallbacks.append(f"{arc.name}/{rd.name}")
            nres = len(list((rd / "results").glob("*"))) if (rd / "results").is_dir() else 0
            rows.append(f"| [`{rid}`]({rd.name}) | {desc} | {nres or '—'} |")
        total_rows += len(rows)
        table = "\n".join([
            BEGIN, "",
            f"**{len(rows)} rounds.** Regenerate with "
            "`.venv/bin/python assurance/generate_round_index.py --apply`; "
            "everything outside the two markers is left untouched.", "",
            "| round | what it asked | results files |", "|---|---|---|",
            *rows, "", END])

        rm = arc / "README.md"
        if rm.exists():
            s = rm.read_text()
            new = BLOCK.sub(lambda _m: table, s) if BLOCK.search(s) else s.rstrip() + "\n\n---\n\n" + table + "\n"
            was = "updated"
        else:
            new = (f"# {arc.name.split('_',1)[0]} — {arc.name.split('_',1)[1].replace('_',' ')}\n\n"
                   "**Created 2026-08-03 by the arc merge.** This arc was assembled from rounds that "
                   "previously sat in single-round arcs, so it inherited no README. Per P16 this file "
                   "is a TABLE OF CONTENTS only — every finding, its interval and its scope live in "
                   "`E05/FORMULATION.md` or the top-level `README.md`.\n\n" + table + "\n")
            was = "CREATED"
        (created if was == "CREATED" else updated).append(arc.name)
        if a.apply:
            rm.write_text(new)
        print(f"    {arc.name[:52]:<54}{len(rows):>7}{was:>10}  "
              f"{', '.join(f'{k}:{v}' for k, v in sorted(srcs.items()))}")

    print(f"\n  {total_rows} rows over {len(created)+len(updated)} arcs · "
          f"{len(created)} README created · {len(updated)} updated")
    print(f"  descriptions that fell back to the SLUG (weakest source, listed not hidden): "
          f"{len(fallbacks)}")
    for f in fallbacks[:8]:
        print(f"    {f}")
    if not a.apply:
        print("\n  dry run — re-run with --apply to write.")
        return 0

    after = coverage()
    print(f"\n  coverage AFTER : {after[0]}/{after[1]}  ({after[0]/after[1]:.0%})   "
          f"[{after[0]-before[0]:+d} rounds]")
    o = ROOT / "assurance" / "results" / "round_index.json"
    o.parent.mkdir(exist_ok=True)
    o.write_text(json.dumps(dict(
        source_sha=hashlib.sha256(pathlib.Path(__file__).read_bytes()).hexdigest()[:16],
        coverage_before=before, coverage_after=after, rows=total_rows,
        readmes_created=created, readmes_updated=updated, slug_fallbacks=fallbacks), indent=1))
    print(f"  artifact {o.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main() or 0)
